# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 RedLemonBe — https://github.com/redlemonbe/Runbound
# cargo-audit configuration
# v0.4.0 — all previously ignored CVEs resolved by the hickory 0.26 / rustls 0.23 upgrade.
# No active ignores.

[advisories]
