// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 RedLemonBe — https://github.com/redlemonbe/Runbound
//! Anycast announcer (slice 2/3).
//!
//! Supervises an `exabgp` child that announces the VIP route over BGP. Announcement is gated
//! on Runbound's health by the **lifetime of the exabgp child**: while healthy, exabgp runs
//! and announces `<address> next-hop self`; on health loss or shutdown the child is killed, the
//! BGP session drops, and the peer withdraws the route (fast drain). This avoids any dependency
//! on `exabgpcli`/named pipes and is exabgp-version-stable.
//!
//! The VIP itself must live on a dummy/lo interface independently (see `docs/anycast.md`) so the
//! slow path can always bind `interface: <VIP>` — this module never touches the interface
//! address, only the BGP advertisement.

use crate::config::parser::AnycastConfig;
use anyhow::{bail, Context, Result};
use std::process::{Child, Command, Stdio};
use tracing::{info, warn};

const CONF_PATH: &str = "/run/runbound-anycast.conf";

/// Render the exabgp configuration for this node from the `anycast:` block.
/// The route is announced statically while the session is up; Runbound controls
/// announce/withdraw by starting/stopping the exabgp child (see [`AnycastAnnouncer`]).
pub fn generate_exabgp_conf(cfg: &AnycastConfig) -> Result<String> {
    if cfg.address.is_empty() || cfg.peer.is_empty() || cfg.local_as == 0 || cfg.peer_as == 0 {
        bail!("anycast: 'address', 'peer', 'local-as' and 'peer-as' are all required");
    }
    let local = cfg.local_address.clone().unwrap_or_default();
    if local.is_empty() {
        bail!("anycast: 'local-address' is required (this node's IP facing the BGP peer)");
    }
    let rid = cfg.router_id.clone().unwrap_or_else(|| local.clone());
    Ok(format!(
        "# Generated by Runbound — do not edit by hand.\n\
         neighbor {peer} {{\n\
         \x20   router-id {rid};\n\
         \x20   local-address {local};\n\
         \x20   local-as {las};\n\
         \x20   peer-as {pas};\n\
         \x20   family {{\n\
         \x20       ipv4 unicast;\n\
         \x20   }}\n\
         \x20   static {{\n\
         \x20       route {addr} next-hop self;\n\
         \x20   }}\n\
         }}\n",
        peer = cfg.peer,
        rid = rid,
        local = local,
        las = cfg.local_as,
        pas = cfg.peer_as,
        addr = cfg.address,
    ))
}

/// Supervises the exabgp child. `announce()` = start (route up); `withdraw()` = stop (route
/// gone). Dropping the announcer withdraws (graceful drain on shutdown).
pub struct AnycastAnnouncer {
    cfg: AnycastConfig,
    child: Option<Child>,
}

impl AnycastAnnouncer {
    /// Validate the config and write `/run/runbound-anycast.conf`. Does not announce yet.
    pub fn prepare(cfg: &AnycastConfig) -> Result<Self> {
        let conf = generate_exabgp_conf(cfg)?;
        std::fs::write(CONF_PATH, &conf).with_context(|| format!("anycast: writing {CONF_PATH}"))?;
        info!(address = %cfg.address, peer = %cfg.peer, local_as = cfg.local_as,
              "anycast: exabgp config written to {CONF_PATH}");
        Ok(Self { cfg: cfg.clone(), child: None })
    }

    fn exabgp_bin(&self) -> String {
        self.cfg.exabgp_path.clone().unwrap_or_else(|| "exabgp".to_string())
    }

    /// Healthy → ensure exabgp is running (route ANNOUNCED). Idempotent.
    pub fn announce(&mut self) -> Result<()> {
        if self.is_announcing() {
            return Ok(());
        }
        let bin = self.exabgp_bin();
        let child = Command::new(&bin)
            .arg(CONF_PATH)
            .stdin(Stdio::null())
            .spawn()
            .with_context(|| format!("anycast: spawning '{bin}' (is exabgp installed and on PATH?)"))?;
        info!(address = %self.cfg.address, pid = child.id(),
              "anycast: exabgp started — route ANNOUNCED");
        self.child = Some(child);
        Ok(())
    }

    /// Unhealthy / draining → stop exabgp (BGP session drops, peer withdraws the route).
    pub fn withdraw(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = child.kill();
            let _ = child.wait();
            warn!(address = %self.cfg.address, "anycast: exabgp stopped — route WITHDRAWN");
        }
    }

    /// True while the exabgp child is alive (route announced).
    pub fn is_announcing(&mut self) -> bool {
        match self.child.as_mut() {
            Some(c) => matches!(c.try_wait(), Ok(None)),
            None => false,
        }
    }
}

impl Drop for AnycastAnnouncer {
    fn drop(&mut self) {
        self.withdraw();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::parser::AnycastConfig;

    fn sample() -> AnycastConfig {
        AnycastConfig {
            address: "198.51.100.53/32".into(),
            local_as: 65001,
            peer: "192.168.1.1".into(),
            peer_as: 65000,
            local_address: Some("192.168.1.10".into()),
            router_id: None,
            exabgp_path: None,
        }
    }

    #[test]
    fn exabgp_conf_has_neighbor_and_route() {
        let conf = generate_exabgp_conf(&sample()).unwrap();
        assert!(conf.contains("neighbor 192.168.1.1 {"), "neighbor block: {conf}");
        assert!(conf.contains("local-as 65001;"));
        assert!(conf.contains("peer-as 65000;"));
        assert!(conf.contains("local-address 192.168.1.10;"));
        assert!(conf.contains("route 198.51.100.53/32 next-hop self;"));
        // router-id defaults to local-address when unset
        assert!(conf.contains("router-id 192.168.1.10;"));
    }

    #[test]
    fn missing_required_fields_rejected() {
        assert!(generate_exabgp_conf(&AnycastConfig::default()).is_err());
        let mut c = sample();
        c.local_address = None; // local-address required
        assert!(generate_exabgp_conf(&c).is_err());
    }
}
